import { useState } from "react";
import { Link } from "wouter";
import { Plus, Loader2, Music2, Sparkles, User } from "lucide-react";
import { useListArtists, useCreateArtist, getListArtistsQueryKey } from "@workspace/api-client-react";
import type { Artist } from "@workspace/api-client-react";
import { queryClient } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { AiGeneratedContentNote } from "@/components/ai-generated-content-note";

function ArtistCard({ artist }: { artist: Artist }) {
  const initials = artist.name
    .split(" ")
    .map((w) => w[0])
    .join("")
    .slice(0, 2)
    .toUpperCase();

  return (
    <Link href={`/artists/${artist.id}`}>
      <Card className="group cursor-pointer hover:shadow-lg transition-all duration-200 hover:-translate-y-0.5 overflow-hidden border border-border/60">
        <div className="relative aspect-square bg-gradient-to-br from-primary/20 via-secondary/20 to-accent/20 overflow-hidden">
          {artist.photoUrl ? (
            <img
              src={artist.photoUrl}
              alt={artist.name}
              className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
            />
          ) : (
            <div className="w-full h-full flex items-center justify-center">
              <span className="font-clash text-4xl font-bold text-primary/60">
                {initials}
              </span>
            </div>
          )}
        </div>
        <CardContent className="p-3">
          <h3 className="font-clash font-bold text-base leading-tight truncate">
            {artist.name}
          </h3>
          {artist.vibeTags && artist.vibeTags.length > 0 && (
            <div className="flex flex-wrap gap-1 mt-1.5">
              {artist.vibeTags.slice(0, 2).map((tag) => (
                <Badge
                  key={tag}
                  variant="secondary"
                  className="text-xs px-1.5 py-0 rounded-full"
                >
                  {tag}
                </Badge>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </Link>
  );
}

function AddArtistDialog({ onCreated }: { onCreated: () => void }) {
  const [open, setOpen] = useState(false);
  const [name, setName] = useState("");
  const { toast } = useToast();

  const createArtist = useCreateArtist({
    mutation: {
      onSuccess: () => {
        queryClient.invalidateQueries({ queryKey: getListArtistsQueryKey() });
        setOpen(false);
        setName("");
        onCreated();
        toast({ title: "Artist added!", description: "Bio and vibe tags generated by AI." });
      },
      onError: () => {
        toast({ title: "Failed to add artist", variant: "destructive" });
      },
    },
  });

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!name.trim()) return;
    createArtist.mutate({ data: { name: name.trim() } });
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button className="rounded-full gap-2">
          <Plus className="w-4 h-4" />
          Add Artist
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-sm">
        <DialogHeader>
          <DialogTitle className="font-clash text-2xl">Add an Artist</DialogTitle>
          <DialogDescription className="flex items-center gap-1.5">
            <Sparkles className="w-3.5 h-3.5 text-yellow-500" />
            Claude will generate a bio and vibe tags automatically.
          </DialogDescription>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4 mt-2">
          <div className="space-y-2">
            <label className="text-sm font-medium" htmlFor="artist-name">
              Artist Name
            </label>
            <Input
              id="artist-name"
              placeholder="e.g. Famous, Emmerson, Rozzy Sokota…"
              value={name}
              onChange={(e) => setName(e.target.value)}
              disabled={createArtist.isPending}
              autoFocus
            />
          </div>
          <Button
            type="submit"
            className="w-full rounded-full"
            disabled={!name.trim() || createArtist.isPending}
          >
            {createArtist.isPending ? (
              <>
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                Generating…
              </>
            ) : (
              <>
                <Sparkles className="w-4 h-4 mr-2" />
                Add &amp; Generate Bio
              </>
            )}
          </Button>
          <AiGeneratedContentNote className="text-center pt-2" />
        </form>
      </DialogContent>
    </Dialog>
  );
}

export function Artists() {
  const { data: artists, isLoading, isError } = useListArtists();

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="font-clash text-3xl md:text-4xl font-bold text-foreground">
            Artists
          </h1>
          <p className="text-muted-foreground mt-1">
            Salone's finest musicians
          </p>
        </div>
        <AddArtistDialog onCreated={() => {}} />
      </div>

      {isLoading && (
        <div className="flex items-center justify-center py-20">
          <Loader2 className="w-8 h-8 animate-spin text-muted-foreground" />
        </div>
      )}

      {isError && (
        <div className="text-center py-20">
          <p className="text-destructive">Failed to load artists. Please try again.</p>
        </div>
      )}

      {!isLoading && !isError && artists?.length === 0 && (
        <div className="flex flex-col items-center justify-center py-20 text-center">
          <div className="w-20 h-20 bg-secondary/10 rounded-full flex items-center justify-center mb-4">
            <Music2 className="w-10 h-10 text-secondary" />
          </div>
          <p className="text-muted-foreground text-lg">No artists yet.</p>
          <p className="text-muted-foreground text-sm mt-1">
            Add the first Salone artist to get started.
          </p>
        </div>
      )}

      {!isLoading && !isError && artists && artists.length > 0 && (
        <>
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-3 md:gap-4">
            {artists.map((artist) => (
              <ArtistCard key={artist.id} artist={artist} />
            ))}
          </div>
          <AiGeneratedContentNote className="max-w-2xl mx-auto text-center border-t border-border/30 pt-6" />
        </>
      )}
    </div>
  );
}
